/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DemandeRouteImport } from './routes/demande'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRapportsIndexRouteImport } from './routes/_authenticated/rapports.index'
import { Route as AuthenticatedPlanningIndexRouteImport } from './routes/_authenticated/planning.index'
import { Route as AuthenticatedEspaceIndexRouteImport } from './routes/_authenticated/espace.index'
import { Route as AuthenticatedDevisIndexRouteImport } from './routes/_authenticated/devis.index'
import { Route as AuthenticatedDemandesIndexRouteImport } from './routes/_authenticated/demandes.index'
import { Route as AuthenticatedRapportsIdRouteImport } from './routes/_authenticated/rapports.$id'
import { Route as AuthenticatedDevisIdRouteImport } from './routes/_authenticated/devis.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandeRoute = DemandeRouteImport.update({
  id: '/demande',
  path: '/demande',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRapportsIndexRoute =
  AuthenticatedRapportsIndexRouteImport.update({
    id: '/rapports/',
    path: '/rapports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanningIndexRoute =
  AuthenticatedPlanningIndexRouteImport.update({
    id: '/planning/',
    path: '/planning/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceIndexRoute =
  AuthenticatedEspaceIndexRouteImport.update({
    id: '/espace/',
    path: '/espace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevisIndexRoute = AuthenticatedDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandesIndexRoute =
  AuthenticatedDemandesIndexRouteImport.update({
    id: '/demandes/',
    path: '/demandes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRapportsIdRoute = AuthenticatedRapportsIdRouteImport.update({
  id: '/rapports/$id',
  path: '/rapports/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevisIdRoute = AuthenticatedDevisIdRouteImport.update({
  id: '/devis/$id',
  path: '/devis/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demande': typeof DemandeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/rapports/$id': typeof AuthenticatedRapportsIdRoute
  '/demandes/': typeof AuthenticatedDemandesIndexRoute
  '/devis/': typeof AuthenticatedDevisIndexRoute
  '/espace/': typeof AuthenticatedEspaceIndexRoute
  '/planning/': typeof AuthenticatedPlanningIndexRoute
  '/rapports/': typeof AuthenticatedRapportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demande': typeof DemandeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/rapports/$id': typeof AuthenticatedRapportsIdRoute
  '/demandes': typeof AuthenticatedDemandesIndexRoute
  '/devis': typeof AuthenticatedDevisIndexRoute
  '/espace': typeof AuthenticatedEspaceIndexRoute
  '/planning': typeof AuthenticatedPlanningIndexRoute
  '/rapports': typeof AuthenticatedRapportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demande': typeof DemandeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/devis/$id': typeof AuthenticatedDevisIdRoute
  '/_authenticated/rapports/$id': typeof AuthenticatedRapportsIdRoute
  '/_authenticated/demandes/': typeof AuthenticatedDemandesIndexRoute
  '/_authenticated/devis/': typeof AuthenticatedDevisIndexRoute
  '/_authenticated/espace/': typeof AuthenticatedEspaceIndexRoute
  '/_authenticated/planning/': typeof AuthenticatedPlanningIndexRoute
  '/_authenticated/rapports/': typeof AuthenticatedRapportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demande'
    | '/sitemap.xml'
    | '/devis/$id'
    | '/rapports/$id'
    | '/demandes/'
    | '/devis/'
    | '/espace/'
    | '/planning/'
    | '/rapports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demande'
    | '/sitemap.xml'
    | '/devis/$id'
    | '/rapports/$id'
    | '/demandes'
    | '/devis'
    | '/espace'
    | '/planning'
    | '/rapports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demande'
    | '/sitemap.xml'
    | '/_authenticated/devis/$id'
    | '/_authenticated/rapports/$id'
    | '/_authenticated/demandes/'
    | '/_authenticated/devis/'
    | '/_authenticated/espace/'
    | '/_authenticated/planning/'
    | '/_authenticated/rapports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemandeRoute: typeof DemandeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demande': {
      id: '/demande'
      path: '/demande'
      fullPath: '/demande'
      preLoaderRoute: typeof DemandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rapports/': {
      id: '/_authenticated/rapports/'
      path: '/rapports'
      fullPath: '/rapports/'
      preLoaderRoute: typeof AuthenticatedRapportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planning/': {
      id: '/_authenticated/planning/'
      path: '/planning'
      fullPath: '/planning/'
      preLoaderRoute: typeof AuthenticatedPlanningIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/': {
      id: '/_authenticated/espace/'
      path: '/espace'
      fullPath: '/espace/'
      preLoaderRoute: typeof AuthenticatedEspaceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devis/': {
      id: '/_authenticated/devis/'
      path: '/devis'
      fullPath: '/devis/'
      preLoaderRoute: typeof AuthenticatedDevisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandes/': {
      id: '/_authenticated/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof AuthenticatedDemandesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapports/$id': {
      id: '/_authenticated/rapports/$id'
      path: '/rapports/$id'
      fullPath: '/rapports/$id'
      preLoaderRoute: typeof AuthenticatedRapportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devis/$id': {
      id: '/_authenticated/devis/$id'
      path: '/devis/$id'
      fullPath: '/devis/$id'
      preLoaderRoute: typeof AuthenticatedDevisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDevisIdRoute: typeof AuthenticatedDevisIdRoute
  AuthenticatedRapportsIdRoute: typeof AuthenticatedRapportsIdRoute
  AuthenticatedDemandesIndexRoute: typeof AuthenticatedDemandesIndexRoute
  AuthenticatedDevisIndexRoute: typeof AuthenticatedDevisIndexRoute
  AuthenticatedEspaceIndexRoute: typeof AuthenticatedEspaceIndexRoute
  AuthenticatedPlanningIndexRoute: typeof AuthenticatedPlanningIndexRoute
  AuthenticatedRapportsIndexRoute: typeof AuthenticatedRapportsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDevisIdRoute: AuthenticatedDevisIdRoute,
  AuthenticatedRapportsIdRoute: AuthenticatedRapportsIdRoute,
  AuthenticatedDemandesIndexRoute: AuthenticatedDemandesIndexRoute,
  AuthenticatedDevisIndexRoute: AuthenticatedDevisIndexRoute,
  AuthenticatedEspaceIndexRoute: AuthenticatedEspaceIndexRoute,
  AuthenticatedPlanningIndexRoute: AuthenticatedPlanningIndexRoute,
  AuthenticatedRapportsIndexRoute: AuthenticatedRapportsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemandeRoute: DemandeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
