/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as InstallerRouteImport } from './routes/installer'
import { Route as DemandeRouteImport } from './routes/demande'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartenaireTokenRouteImport } from './routes/partenaire.$token'
import { Route as FactureClientTokenRouteImport } from './routes/facture-client.$token'
import { Route as DevisClientTokenRouteImport } from './routes/devis-client.$token'
import { Route as AuthenticatedRealisationsIndexRouteImport } from './routes/_authenticated/realisations.index'
import { Route as AuthenticatedRapportsIndexRouteImport } from './routes/_authenticated/rapports.index'
import { Route as AuthenticatedPlanningIndexRouteImport } from './routes/_authenticated/planning.index'
import { Route as AuthenticatedPartenairesIndexRouteImport } from './routes/_authenticated/partenaires.index'
import { Route as AuthenticatedFacturesIndexRouteImport } from './routes/_authenticated/factures.index'
import { Route as AuthenticatedEspaceIndexRouteImport } from './routes/_authenticated/espace.index'
import { Route as AuthenticatedDevisIndexRouteImport } from './routes/_authenticated/devis.index'
import { Route as AuthenticatedDemandesIndexRouteImport } from './routes/_authenticated/demandes.index'
import { Route as AuthenticatedRapportsIdRouteImport } from './routes/_authenticated/rapports.$id'
import { Route as AuthenticatedFacturesIdRouteImport } from './routes/_authenticated/factures.$id'
import { Route as AuthenticatedDevisIdRouteImport } from './routes/_authenticated/devis.$id'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicPhotoSplatRouteImport } from './routes/api/public/photo.$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallerRoute = InstallerRouteImport.update({
  id: '/installer',
  path: '/installer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandeRoute = DemandeRouteImport.update({
  id: '/demande',
  path: '/demande',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenaireTokenRoute = PartenaireTokenRouteImport.update({
  id: '/partenaire/$token',
  path: '/partenaire/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FactureClientTokenRoute = FactureClientTokenRouteImport.update({
  id: '/facture-client/$token',
  path: '/facture-client/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisClientTokenRoute = DevisClientTokenRouteImport.update({
  id: '/devis-client/$token',
  path: '/devis-client/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRealisationsIndexRoute =
  AuthenticatedRealisationsIndexRouteImport.update({
    id: '/realisations/',
    path: '/realisations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRapportsIndexRoute =
  AuthenticatedRapportsIndexRouteImport.update({
    id: '/rapports/',
    path: '/rapports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanningIndexRoute =
  AuthenticatedPlanningIndexRouteImport.update({
    id: '/planning/',
    path: '/planning/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartenairesIndexRoute =
  AuthenticatedPartenairesIndexRouteImport.update({
    id: '/partenaires/',
    path: '/partenaires/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacturesIndexRoute =
  AuthenticatedFacturesIndexRouteImport.update({
    id: '/factures/',
    path: '/factures/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceIndexRoute =
  AuthenticatedEspaceIndexRouteImport.update({
    id: '/espace/',
    path: '/espace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevisIndexRoute = AuthenticatedDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandesIndexRoute =
  AuthenticatedDemandesIndexRouteImport.update({
    id: '/demandes/',
    path: '/demandes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRapportsIdRoute = AuthenticatedRapportsIdRouteImport.update({
  id: '/rapports/$id',
  path: '/rapports/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacturesIdRoute = AuthenticatedFacturesIdRouteImport.update({
  id: '/factures/$id',
  path: '/factures/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevisIdRoute = AuthenticatedDevisIdRouteImport.update({
  id: '/devis/$id',
  path: '/devis/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPhotoSplatRoute = ApiPublicPhotoSplatRouteImport.update({
  id: '/api/public/photo/$',
  path: '/api/public/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demande': typeof DemandeRoute
  '/installer': typeof InstallerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/devis-client/$token': typeof DevisClientTokenRoute
  '/facture-client/$token': typeof FactureClientTokenRoute
  '/partenaire/$token': typeof PartenaireTokenRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/factures/$id': typeof AuthenticatedFacturesIdRoute
  '/rapports/$id': typeof AuthenticatedRapportsIdRoute
  '/demandes/': typeof AuthenticatedDemandesIndexRoute
  '/devis/': typeof AuthenticatedDevisIndexRoute
  '/espace/': typeof AuthenticatedEspaceIndexRoute
  '/factures/': typeof AuthenticatedFacturesIndexRoute
  '/partenaires/': typeof AuthenticatedPartenairesIndexRoute
  '/planning/': typeof AuthenticatedPlanningIndexRoute
  '/rapports/': typeof AuthenticatedRapportsIndexRoute
  '/realisations/': typeof AuthenticatedRealisationsIndexRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demande': typeof DemandeRoute
  '/installer': typeof InstallerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/devis-client/$token': typeof DevisClientTokenRoute
  '/facture-client/$token': typeof FactureClientTokenRoute
  '/partenaire/$token': typeof PartenaireTokenRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/factures/$id': typeof AuthenticatedFacturesIdRoute
  '/rapports/$id': typeof AuthenticatedRapportsIdRoute
  '/demandes': typeof AuthenticatedDemandesIndexRoute
  '/devis': typeof AuthenticatedDevisIndexRoute
  '/espace': typeof AuthenticatedEspaceIndexRoute
  '/factures': typeof AuthenticatedFacturesIndexRoute
  '/partenaires': typeof AuthenticatedPartenairesIndexRoute
  '/planning': typeof AuthenticatedPlanningIndexRoute
  '/rapports': typeof AuthenticatedRapportsIndexRoute
  '/realisations': typeof AuthenticatedRealisationsIndexRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demande': typeof DemandeRoute
  '/installer': typeof InstallerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/devis-client/$token': typeof DevisClientTokenRoute
  '/facture-client/$token': typeof FactureClientTokenRoute
  '/partenaire/$token': typeof PartenaireTokenRoute
  '/_authenticated/devis/$id': typeof AuthenticatedDevisIdRoute
  '/_authenticated/factures/$id': typeof AuthenticatedFacturesIdRoute
  '/_authenticated/rapports/$id': typeof AuthenticatedRapportsIdRoute
  '/_authenticated/demandes/': typeof AuthenticatedDemandesIndexRoute
  '/_authenticated/devis/': typeof AuthenticatedDevisIndexRoute
  '/_authenticated/espace/': typeof AuthenticatedEspaceIndexRoute
  '/_authenticated/factures/': typeof AuthenticatedFacturesIndexRoute
  '/_authenticated/partenaires/': typeof AuthenticatedPartenairesIndexRoute
  '/_authenticated/planning/': typeof AuthenticatedPlanningIndexRoute
  '/_authenticated/rapports/': typeof AuthenticatedRapportsIndexRoute
  '/_authenticated/realisations/': typeof AuthenticatedRealisationsIndexRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demande'
    | '/installer'
    | '/sitemap.xml'
    | '/devis-client/$token'
    | '/facture-client/$token'
    | '/partenaire/$token'
    | '/devis/$id'
    | '/factures/$id'
    | '/rapports/$id'
    | '/demandes/'
    | '/devis/'
    | '/espace/'
    | '/factures/'
    | '/partenaires/'
    | '/planning/'
    | '/rapports/'
    | '/realisations/'
    | '/api/public/photo/$'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demande'
    | '/installer'
    | '/sitemap.xml'
    | '/devis-client/$token'
    | '/facture-client/$token'
    | '/partenaire/$token'
    | '/devis/$id'
    | '/factures/$id'
    | '/rapports/$id'
    | '/demandes'
    | '/devis'
    | '/espace'
    | '/factures'
    | '/partenaires'
    | '/planning'
    | '/rapports'
    | '/realisations'
    | '/api/public/photo/$'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demande'
    | '/installer'
    | '/sitemap.xml'
    | '/devis-client/$token'
    | '/facture-client/$token'
    | '/partenaire/$token'
    | '/_authenticated/devis/$id'
    | '/_authenticated/factures/$id'
    | '/_authenticated/rapports/$id'
    | '/_authenticated/demandes/'
    | '/_authenticated/devis/'
    | '/_authenticated/espace/'
    | '/_authenticated/factures/'
    | '/_authenticated/partenaires/'
    | '/_authenticated/planning/'
    | '/_authenticated/rapports/'
    | '/_authenticated/realisations/'
    | '/api/public/photo/$'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemandeRoute: typeof DemandeRoute
  InstallerRoute: typeof InstallerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DevisClientTokenRoute: typeof DevisClientTokenRoute
  FactureClientTokenRoute: typeof FactureClientTokenRoute
  PartenaireTokenRoute: typeof PartenaireTokenRoute
  ApiPublicPhotoSplatRoute: typeof ApiPublicPhotoSplatRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installer': {
      id: '/installer'
      path: '/installer'
      fullPath: '/installer'
      preLoaderRoute: typeof InstallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demande': {
      id: '/demande'
      path: '/demande'
      fullPath: '/demande'
      preLoaderRoute: typeof DemandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaire/$token': {
      id: '/partenaire/$token'
      path: '/partenaire/$token'
      fullPath: '/partenaire/$token'
      preLoaderRoute: typeof PartenaireTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facture-client/$token': {
      id: '/facture-client/$token'
      path: '/facture-client/$token'
      fullPath: '/facture-client/$token'
      preLoaderRoute: typeof FactureClientTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis-client/$token': {
      id: '/devis-client/$token'
      path: '/devis-client/$token'
      fullPath: '/devis-client/$token'
      preLoaderRoute: typeof DevisClientTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/realisations/': {
      id: '/_authenticated/realisations/'
      path: '/realisations'
      fullPath: '/realisations/'
      preLoaderRoute: typeof AuthenticatedRealisationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapports/': {
      id: '/_authenticated/rapports/'
      path: '/rapports'
      fullPath: '/rapports/'
      preLoaderRoute: typeof AuthenticatedRapportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planning/': {
      id: '/_authenticated/planning/'
      path: '/planning'
      fullPath: '/planning/'
      preLoaderRoute: typeof AuthenticatedPlanningIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partenaires/': {
      id: '/_authenticated/partenaires/'
      path: '/partenaires'
      fullPath: '/partenaires/'
      preLoaderRoute: typeof AuthenticatedPartenairesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factures/': {
      id: '/_authenticated/factures/'
      path: '/factures'
      fullPath: '/factures/'
      preLoaderRoute: typeof AuthenticatedFacturesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/': {
      id: '/_authenticated/espace/'
      path: '/espace'
      fullPath: '/espace/'
      preLoaderRoute: typeof AuthenticatedEspaceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devis/': {
      id: '/_authenticated/devis/'
      path: '/devis'
      fullPath: '/devis/'
      preLoaderRoute: typeof AuthenticatedDevisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandes/': {
      id: '/_authenticated/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof AuthenticatedDemandesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapports/$id': {
      id: '/_authenticated/rapports/$id'
      path: '/rapports/$id'
      fullPath: '/rapports/$id'
      preLoaderRoute: typeof AuthenticatedRapportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factures/$id': {
      id: '/_authenticated/factures/$id'
      path: '/factures/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof AuthenticatedFacturesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devis/$id': {
      id: '/_authenticated/devis/$id'
      path: '/devis/$id'
      fullPath: '/devis/$id'
      preLoaderRoute: typeof AuthenticatedDevisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/photo/$': {
      id: '/api/public/photo/$'
      path: '/api/public/photo/$'
      fullPath: '/api/public/photo/$'
      preLoaderRoute: typeof ApiPublicPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDevisIdRoute: typeof AuthenticatedDevisIdRoute
  AuthenticatedFacturesIdRoute: typeof AuthenticatedFacturesIdRoute
  AuthenticatedRapportsIdRoute: typeof AuthenticatedRapportsIdRoute
  AuthenticatedDemandesIndexRoute: typeof AuthenticatedDemandesIndexRoute
  AuthenticatedDevisIndexRoute: typeof AuthenticatedDevisIndexRoute
  AuthenticatedEspaceIndexRoute: typeof AuthenticatedEspaceIndexRoute
  AuthenticatedFacturesIndexRoute: typeof AuthenticatedFacturesIndexRoute
  AuthenticatedPartenairesIndexRoute: typeof AuthenticatedPartenairesIndexRoute
  AuthenticatedPlanningIndexRoute: typeof AuthenticatedPlanningIndexRoute
  AuthenticatedRapportsIndexRoute: typeof AuthenticatedRapportsIndexRoute
  AuthenticatedRealisationsIndexRoute: typeof AuthenticatedRealisationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDevisIdRoute: AuthenticatedDevisIdRoute,
  AuthenticatedFacturesIdRoute: AuthenticatedFacturesIdRoute,
  AuthenticatedRapportsIdRoute: AuthenticatedRapportsIdRoute,
  AuthenticatedDemandesIndexRoute: AuthenticatedDemandesIndexRoute,
  AuthenticatedDevisIndexRoute: AuthenticatedDevisIndexRoute,
  AuthenticatedEspaceIndexRoute: AuthenticatedEspaceIndexRoute,
  AuthenticatedFacturesIndexRoute: AuthenticatedFacturesIndexRoute,
  AuthenticatedPartenairesIndexRoute: AuthenticatedPartenairesIndexRoute,
  AuthenticatedPlanningIndexRoute: AuthenticatedPlanningIndexRoute,
  AuthenticatedRapportsIndexRoute: AuthenticatedRapportsIndexRoute,
  AuthenticatedRealisationsIndexRoute: AuthenticatedRealisationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemandeRoute: DemandeRoute,
  InstallerRoute: InstallerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DevisClientTokenRoute: DevisClientTokenRoute,
  FactureClientTokenRoute: FactureClientTokenRoute,
  PartenaireTokenRoute: PartenaireTokenRoute,
  ApiPublicPhotoSplatRoute: ApiPublicPhotoSplatRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
